In [1]:
from pyunpack import Archive
import numpy as np
import pandas as pd
import os
import cv2
import keras
import matplotlib.pyplot as plt

Using TensorFlow backend.


In [2]:
path=r'C:\Users\csc\Downloads\leapgestrecog\leapGestRecog'

categories=['01_palm','02_l','03_fist','04_fist_moved','05_thumb','06_index','07_ok','08_palm_moved','09_c','10_down']

In [166]:
data=[]
for folder in os.listdir(path):
    new_folder=os.path.join(path,folder)
    for class_n in os.listdir(new_folder):
        clas=categories.index(class_n)
        new_class=os.path.join(new_folder,class_n)
        for img in os.listdir(new_class):
            img_array=cv2.imread(os.path.join(new_class,img),1)
            gray=cv2.cvtColor(img_array,cv2.COLOR_BGR2GRAY)
            new_array=cv2.resize(gray,(224,224))
            data.append([new_array,clas])
            #print(data)
            #plt.imshow(img_array)
            #plt.show()
      
data

[[array([[ 5,  5,  4, ...,  5,  3,  6],
         [ 4,  5,  4, ...,  3,  3,  2],
         [ 5,  4,  4, ...,  2,  3,  2],
         ...,
         [ 5,  3,  4, ...,  6,  3,  4],
         [ 5,  4,  4, ...,  6,  4,  3],
         [ 5,  4,  4, ...,  4, 11, 12]], dtype=uint8), 0],
 [array([[ 5,  3,  4, ...,  4,  4,  3],
         [ 3,  4,  4, ...,  2,  2,  2],
         [ 3,  3,  4, ...,  4,  3,  4],
         ...,
         [ 5,  5,  6, ...,  4,  4,  5],
         [ 3,  6,  7, ...,  4,  5,  3],
         [ 5,  6,  5, ...,  4, 12, 12]], dtype=uint8), 0],
 [array([[ 5,  3,  4, ...,  4,  4,  3],
         [ 3,  4,  4, ...,  2,  2,  2],
         [ 3,  3,  4, ...,  4,  3,  4],
         ...,
         [ 5,  5,  6, ...,  4,  4,  5],
         [ 3,  6,  7, ...,  4,  5,  3],
         [ 5,  6,  5, ...,  4, 12, 12]], dtype=uint8), 0],
 [array([[ 4,  4,  4, ...,  4,  3,  2],
         [ 4,  7,  4, ...,  3,  5,  3],
         [ 4,  4,  5, ...,  3,  3,  3],
         ...,
         [ 5,  4,  5, ...,  4,  4,  4],
       

In [167]:
data

[[array([[ 5,  5,  4, ...,  5,  3,  6],
         [ 4,  5,  4, ...,  3,  3,  2],
         [ 5,  4,  4, ...,  2,  3,  2],
         ...,
         [ 5,  3,  4, ...,  6,  3,  4],
         [ 5,  4,  4, ...,  6,  4,  3],
         [ 5,  4,  4, ...,  4, 11, 12]], dtype=uint8), 0],
 [array([[ 5,  3,  4, ...,  4,  4,  3],
         [ 3,  4,  4, ...,  2,  2,  2],
         [ 3,  3,  4, ...,  4,  3,  4],
         ...,
         [ 5,  5,  6, ...,  4,  4,  5],
         [ 3,  6,  7, ...,  4,  5,  3],
         [ 5,  6,  5, ...,  4, 12, 12]], dtype=uint8), 0],
 [array([[ 5,  3,  4, ...,  4,  4,  3],
         [ 3,  4,  4, ...,  2,  2,  2],
         [ 3,  3,  4, ...,  4,  3,  4],
         ...,
         [ 5,  5,  6, ...,  4,  4,  5],
         [ 3,  6,  7, ...,  4,  5,  3],
         [ 5,  6,  5, ...,  4, 12, 12]], dtype=uint8), 0],
 [array([[ 4,  4,  4, ...,  4,  3,  2],
         [ 4,  7,  4, ...,  3,  5,  3],
         [ 4,  4,  5, ...,  3,  3,  3],
         ...,
         [ 5,  4,  5, ...,  4,  4,  4],
       

In [168]:
import random
random.shuffle(data)

In [169]:
train=data[:15000]
validation=data[15000:17000]
test=data[15000:]

In [173]:
def onehot_encoding(Y):
    one_hot=np.zeros((len(Y),10))

    for idx,num in enumerate(Y):
        one_hot[idx][num]=1
    #print(one_hot)
    return one_hot

In [174]:
train_x=[]
train_y=[]
test_x=[]
test_y=[]

In [175]:
for features,labels in train:
    train_x.append(features)
    train_y.append(labels)
train_x=np.array(train_x).reshape([-1,224,224,1])
train_y=onehot_encoding(train_y)
    
for features,labels in test:
    test_x.append(features)
    test_y.append(labels)
test_x=np.array(test_x).reshape(-1,224,224,1)
test_y=onehot_encoding(test_y)

print(train_x)

[[[[ 6]
   [ 5]
   [ 4]
   ...
   [ 4]
   [ 4]
   [ 4]]

  [[ 5]
   [ 5]
   [ 5]
   ...
   [ 3]
   [ 3]
   [ 4]]

  [[ 4]
   [ 4]
   [ 3]
   ...
   [ 3]
   [ 3]
   [ 4]]

  ...

  [[ 5]
   [ 4]
   [ 4]
   ...
   [ 4]
   [ 4]
   [ 5]]

  [[ 6]
   [ 5]
   [ 5]
   ...
   [ 3]
   [ 4]
   [ 5]]

  [[ 4]
   [ 5]
   [ 4]
   ...
   [ 3]
   [ 6]
   [12]]]


 [[[ 6]
   [ 6]
   [ 6]
   ...
   [ 4]
   [ 5]
   [ 2]]

  [[ 5]
   [ 5]
   [ 6]
   ...
   [ 4]
   [ 4]
   [ 3]]

  [[ 7]
   [ 5]
   [ 6]
   ...
   [ 5]
   [ 5]
   [ 4]]

  ...

  [[ 7]
   [ 5]
   [ 6]
   ...
   [ 5]
   [ 4]
   [ 6]]

  [[ 7]
   [ 6]
   [ 4]
   ...
   [ 5]
   [ 6]
   [ 6]]

  [[ 5]
   [ 5]
   [ 5]
   ...
   [ 5]
   [ 4]
   [12]]]


 [[[ 6]
   [ 5]
   [ 5]
   ...
   [ 7]
   [ 6]
   [ 6]]

  [[ 4]
   [ 5]
   [ 4]
   ...
   [ 6]
   [ 6]
   [ 6]]

  [[ 5]
   [ 4]
   [ 4]
   ...
   [ 6]
   [ 5]
   [ 6]]

  ...

  [[ 4]
   [ 4]
   [ 4]
   ...
   [ 5]
   [ 6]
   [ 4]]

  [[ 3]
   [ 4]
   [ 4]
   ...
   [ 6]
   [ 5]
   [ 6]]

  [[ 4

In [176]:
'''X=[]
Y=[]

for features,labels in data:
    X.append(features)
    Y.append(labels)
X = np.array(X)
X=X.reshape([-1,200,200,1])
#X = X.astype('float32') / 255
print(len(X))
print(len(data))'''

"X=[]\nY=[]\n\nfor features,labels in data:\n    X.append(features)\n    Y.append(labels)\nX = np.array(X)\nX=X.reshape([-1,200,200,1])\n#X = X.astype('float32') / 255\nprint(len(X))\nprint(len(data))"

In [177]:
X

NameError: name 'X' is not defined

In [178]:
from sklearn.model_selection import train_test_split

(trainX, testX, trainY, testY) = train_test_split(X,one_hot, test_size=0.25, random_state=42)

NameError: name 'X' is not defined

In [179]:
print(len(trainX))
trainX.reshape([-1,200,200,1])

NameError: name 'trainX' is not defined

In [180]:
from keras.models import Sequential
from keras.layers import Conv2D,MaxPooling2D,Dense,Flatten,Dropout,Activation


In [181]:
'''model=Sequential()

model.add(Conv2D(32,(3,3),activation='relu',input_shape=(100,100,1)))
model.add(MaxPooling2D((2,2)))

model.add(Conv2D(64,(3,3),activation='relu'))
model.add(MaxPooling2D((2,2)))

model.add(Conv2D(128,(3,3),activation='relu'))
model.add(MaxPooling2D((2,2)))

model.add(Conv2D(128,(3,3),activation='relu'))
model.add(MaxPooling2D((2,2)))

model.add(Flatten())
model.add(Dropout(0.1))
model.add(Dense(512,activation='relu'))
#model.add(Dense(10,activation='relu'))
model.add(Dense(10,activation='softmax'))


SyntaxError: EOF while scanning triple-quoted string literal (<ipython-input-181-b64822bca7a0>, line 19)

In [184]:
model = Sequential()

# 1st Convolutional Layer
model.add(Conv2D(filters=96, input_shape=(224,224,1), kernel_size=(11,11), strides=(4,4)))
model.add(Activation('relu'))
# Max Pooling
model.add(MaxPooling2D(pool_size=(2,2), strides=(2,2), padding='valid'))

# 2nd Convolutional Layer
model.add(Conv2D(filters=256, kernel_size=(11,11), strides=(1,1), padding='valid'))
model.add(Activation('relu'))
# Max Pooling
model.add(MaxPooling2D(pool_size=(2,2), strides=(2,2), padding='valid'))

# 3rd Convolutional Layer
model.add(Conv2D(filters=384, kernel_size=(3,3), strides=(1,1), padding='valid'))
model.add(Activation('relu'))


# 4th Convolutional Layer
model.add(Conv2D(filters=384, kernel_size=(3,3), strides=(1,1), padding='valid'))
model.add(Activation('relu'))

# 5th Convolutional Layer
model.add(Conv2D(filters=256, kernel_size=(3,3), strides=(1,1), padding='valid'))
model.add(Activation('relu'))
# Max Pooling
model.add(MaxPooling2D(pool_size=(2,2), strides=(2,2), padding='valid'))

# Passing it to a Fully Connected layer
model.add(Flatten())
# 1st Fully Connected Layer
model.add(Dense(4096, input_shape=(224*224*3,)))
model.add(Activation('relu'))
# Add Dropout to prevent overfitting
model.add(Dropout(0.4))

# 2nd Fully Connected Layer
model.add(Dense(4096))
model.add(Activation('relu'))
# Add Dropout
model.add(Dropout(0.4))

# 3rd Fully Connected Layer
model.add(Dense(1000))
model.add(Activation('relu'))
# Add Dropout
model.add(Dropout(0.4))

# Output Layer
model.add(Dense(10))
model.add(Activation('softmax'))

In [185]:
model.compile(loss='categorical_crossentropy',optimizer='adam',metrics=['accuracy'])

In [ ]:
model.fit(train_x,train_y,epochs=3,batch_size=900,validation_data=(test_x, test_y))


Train on 15000 samples, validate on 3000 samples
Epoch 1/3
 6300/15000 [===========>..................] - ETA: 1:41:23 - loss: 3.0299 - acc: 0.13 - ETA: 1:00:08 - loss: 8.6770 - acc: 0.12 - ETA: 44:39 - loss: 10.6798 - acc: 0.1107 - ETA: 37:23 - loss: 11.6946 - acc: 0.104 - ETA: 31:36 - loss: 12.2319 - acc: 0.105 - ETA: 26:53 - loss: 12.5841 - acc: 0.105 - ETA: 23:40 - loss: 12.8715 - acc: 0.1043